name: Docker Image CI

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual workflow triggers

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Log in to Docker Hub (you'll need to add these credentials to GitHub Secrets)
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Extract environment variables from the secret
      - name: Create .env file
        run: |
          echo "${{ secrets.FLASK_ENV_FILE }}" > .env

      # Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: your_dockerhub_username/emby-session-monitor:latest

      # Clean up the environment
      - name: Remove .env file
        run: rm .env
